# For launching a selenium container for testing
version: '2.3'

services:
  selenium:
    image: selenium/standalone-chrome-debug:3.141.59-selenium
    network_mode: "host"
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"
      - "5900:5900"
    environment:
      # Disable the password for now, since we are just debugging
      - VNC_NO_PASSWORD=1
